version: '3'
services:
  client:
    container_name: tranquill_client
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/tranquill/client/src
      - ./client/public:/tranquill/client/public
    command: npm start
