version: '3'
services:
  client:
    container_name: tranquill_client
    build: ./client
    restart: always
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/tranquill/client/src
      - ./client/public:/tranquill/client/public
    links:
      - api
    command: npm start
  api:
    container_name: tranquill_api
    build: ./api
    restart: always
    environment:
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - API_URL=${API_URL}
      - CLIENT_URL=${CLIENT_URL}
      - CLIENT_HOST=${CLIENT_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB=${REDIS_DB}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api/src:/tranquill/api/src
      - ./api/lib:/tranquill/api/lib
      - ./api/test:/tranquill/api/test
    links:
      - mongodb
      - redis
    command: npm start
  mongodb:
    container_name: mongodb
    image: mongo
    expose:
      - ${MONGO_DB_PORT}
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
  redis:
    container_name: redis
    image: redis
    expose:
      - ${REDIS_PORT}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
