apiVersion: apps/v1
kind: Deployment
metadata:
  name: tranquill-client
  labels:
    app: tranquill-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tranquill-client
  template:
    metadata:
      labels:
        app: tranquill-client
    spec:
      containers:
      - name: tranquill-client
        image: us.gcr.io/tranquill/tranquill_client:c43397408342fc9d24c4c2aed909691334dbe54e
        env:
        - name: REACT_APP_ENV
          value: "production"
        - name: REACT_APP_API_URL
          value: "https://api.tranquillapp.com"
        - name: CLIENT_PORT
          value: "5000"
        - name: CLIENT_HOST
          value: "tranquillapp.com"
        command: ["npm", "run", "start:production"]
