apiVersion: apps/v1
kind: Deployment
metadata:
  name: tranquill-client
  labels:
    app: tranquill-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tranquill-client
  template:
    metadata:
      labels:
        app: tranquill-client
    spec:
      containers:
      - name: tranquill-client
        image: us.gcr.io/tranquill/tranquill_client@sha256:f644b3aa474c8cc5cec701d736ca7b81c6aa34526719dd1861f791c0e1e97439
        command: ["npm", "run", "start:production"]
