steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'client'
  id: 'client-npm-install'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'client'
  env:
  - 'REACT_APP_ENV=staging'
  - 'REACT_APP_API_URL=https://staging-api.tranquillapp.com'
  id: 'build-client-bundle'
  waitFor: ['client-npm-install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/staging_client:$REVISION_ID', '.']
  dir: 'client'
  id: 'build-client-image'
  waitFor: ['build-client-bundle']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/staging_client:$REVISION_ID']
  dir: 'client'
  id: 'push-client-image'
  waitFor: ['build-client-image']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/staging_api:$REVISION_ID', '.']
  dir: 'api'
  id: 'build-api-image'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/staging_api:$REVISION_ID']
  dir: 'api'
  id: 'push-api-image'
  waitFor: ['build-api-image']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/staging-client', 'staging-client=us.gcr.io/$PROJECT_ID/staging_client:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tranquill'
  dir: 'client'
  waitFor: ['push-client-image', 'push-api-image']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/staging-api', 'staging-api=us.gcr.io/$PROJECT_ID/staging_api:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tranquill'
  dir: 'api'
  waitFor: ['push-client-image', 'push-api-image']

tags: ['${_ENV}']
