apiVersion: v1
kind: Service
metadata:
  labels:
    app: staging-api
  name: staging-api
spec:
  type: NodePort
  selector:
    app: staging-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
