apiVersion: v1
kind: Service
metadata:
  name: staging-mongo
  labels:
    app: staging-mongo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: staging-mongo
  ports:
  - port: 27018
    name: staging-mongo
    targetPort: 27017
