apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: staging-redis
spec:
  selector:
    matchLabels:
      app: staging-redis
  serviceName: staging-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-redis
    spec:
      containers:
      - name: staging-redis
        image: redis:5.0.3-alpine
        ports:
        - containerPort: 6379
          name: staging-redis
