apiVersion: v1
kind: Service
metadata:
  labels:
    app: staging-client
  name: staging-client
spec:
  type: NodePort
  selector:
    app: staging-client
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5000
